### ISSUE TITLE
composer require failed

### ISSUE THREAD

**Issue by tobischulz** [gregoriohc/laravel-plesk#2]
`Problem 1
    - Installation request for gregoriohc/laravel-plesk ^0.1.0 -> satisfiable by gregoriohc/laravel-plesk[0.1].
    - gregoriohc/laravel-plesk 0.1 requires plesk/api-php-lib @dev -> no matching package found.`

**Comment by poxin13** [comment]
Under "require-dev" in composer.json:

```
"plesk/api-php-lib": "@dev",
"gregoriohc/laravel-plesk": "@dev"
```

worked for me at least.
